name: Build and upload to PyPI

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # macos-13 is an intel runner, macos-14 is apple silicon
        os:
          - ubuntu-latest
          #- windows-latest
          #- macos-13
          #- macos-14]

    steps:
      - uses: actions/checkout@v4
      - uses: pypa/cibuildwheel@v2.21.1
      - uses: actions/upload-artifact@v4
        with:
          name: dist-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
          retention-days: 7

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build sdist
        run: pipx run build --sdist
      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist/*.tar.gz
          retention-days: 7

  publish_pypi:
    name: Publish to PyPI
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment: pypi-publish
    permissions:
      attestations: write
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all dist artifacts into dist/
          pattern: dist-*
          path: dist
          merge-multiple: true

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: dist/pygpgme-*

      - uses: pypa/gh-action-pypi-publish@release/v1
