on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          sudo apt-get install libgpgme-dev
      - name: Build extension
        run: pip install -U .
      - name: Run tests
        run: python -m unittest discover -v tests
